config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # OmniAuth認証後、email入力を求める処理のため。
  match '/users/:id/finish_signup' => 'omniauth_finished#finish_signup', via: %i[get patch], as: :finish_signup

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'projects#index'
  get '/:ticket_number', to: 'projects#show_with_ticket_number', ticket_number: /[A-Za-z]+-[0-9]+/

  resources :projects do
    resources :sprints, constraints: { format: :json }
    get '/api/closed_sprints', to: 'sprints#closed_sprints', as: 'closed_sprints_api'
    get '/sprints/:id/kanban', to: 'sprints#kanban', as: 'sprint_kanban'
    get '/sprints/:id/kanban/api', to: 'sprints#kanban_api'

    resources :project_ticket_categories, constraints: { format: :json }
    resources :project_ticket_statuses, constraints: { format: :json }

    resources :stories, controller: :tickets, type: Story, constraints: { format: :json } do
      resources :comments
    end
    resources :tasks, controller: :tickets, type: Task, constraints: { format: :json } do
      resources :comments
    end
    member do
      get 'closed_sprints'
      get 'settings'

      get 'users'
      get 'groups'
      get 'project_tags'

      post 'add_group'
      delete 'delete_group/:group_id', action: 'delete_group'
      delete 'delete_image'
    end
  end

  get '/groups_by_name', to: 'groups#search_by_name'

  get '/profiles', to: 'profiles#index'
  patch '/profiles', to: 'profiles#update'
  patch '/profiles/update_password', to: 'profiles#update_password'
  # patch '/profiles/use_gravatar', to: 'profiles#use_gravatar'
  delete '/profiles/image', to: 'profiles#destroy_image'

  namespace :application_settings do
    root to: 'dashboard#index'
    get '/', to: 'dashboard#index'
    post '/', to: 'dashboard#update'

    patch 'group_managements/:id/add_user', to: 'group_managements#add_user', as: 'group_managements_add_user'
    delete 'group_managements/:id/remove_user/:user_id', to: 'group_managements#remove_user',
                                                         as: 'group_managements_remove_user'
    resources :group_managements

    patch 'user_managements/:id/update_role', to: 'user_managements#update_role', as: 'user_managements_update_role'
    delete 'user_managements/:id/destroy_image', to: 'user_managements#destroy_image',
                                                 as: 'user_managements_destroy_image'
    resources :user_managements
  end

  get '/installer', to: 'installer#index', as: 'installer'
  match '/installer', to: 'installer#update', via: %i[post patch]

  get '/health', to: 'health#health'

  # 開発環境でメールを確認するために LetterOpenerWeb エンジンのパスをマウントする
  # これにより以下 URL で開発環境でのメール確認が可能になる
  # http://localhost:3000/letter_opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/application_settings/dashboard_controller.rb
class ApplicationSettings::DashboardController < ApplicationController
  authorize_resource class: false

  def index
  end

  def update
    settings_params.keys.each do |key|
      Setting.send("#{key}=", settings_params[key].strip) unless settings_params[key].nil?
    end

    redirect_to application_settings_path, notice: 'Setting was successfully updated.'
  end

  private

  def settings_params
    params.require(:settings).permit(:site_title, :head_custom_script, :body_custom_script)
  end
end

app/controllers/application_settings/group_managements_controller.rb
class ApplicationSettings::GroupManagementsController < ApplicationController
  authorize_resource class: false

  before_action :set_group, only: [
    :show, :edit, :update, :destroy, :add_user, :remove_user
  ]

  GROUP_PER_PAGE = 25

  def index
    @groups = Group.page(params[:page]).per(GROUP_PER_PAGE)

    @group = Group.new
  end

  def show
    @addable_users = User.where.not(id: @group.users)
  end

  def new
    @group = Group.new
  end

  def create
    @groups = Group.all

    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to application_settings_group_managements_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :index }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to application_settings_group_managements_path, notice: 'Group was successfully destroyed.' }
      format.json { render :show, status: :ok, location: @group }
    end
  end

  def add_user
    user = User.find_by(id: group_params[:user_id])
    if user.present?
      @group.users << user

      respond_to do |format|
        format.html { redirect_to application_settings_group_management_path(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      end
    else
      @addable_users = User.where.not(id: @group.users)
      render :show
    end
  end

  def remove_user
    @group.users.destroy(User.find(params[:user_id]))

    respond_to do |format|
      format.html { redirect_to application_settings_group_management_path(@group), notice: 'Group was successfully updated.' }
      format.json { render :show, status: :ok, location: @group }
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :user_id)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/application_settings/user_managements_controller.rb
class ApplicationSettings::UserManagementsController < ApplicationController
  authorize_resource class: false
  before_action :set_user, only: [
    :show, :update, :edit, :destroy,
    :update_role, :destroy_image
  ]

  USER_PER_PAGE = 25

  def index
    @users = User.page(params[:page]).per(USER_PER_PAGE)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_application_settings_user_management_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to application_settings_user_managements_path, notice: 'User was successfully destroyed.' }
      format.json { render :show, status: :ok, location: @user }
    end
  end

  def update_role
    unless Role::ALL_ROLES.include?(user_params[:role].to_sym)
      redirect_to edit_application_settings_user_management_path(@user), notice: 'User was successfully updated.'
    end

    # remove all role
    roles = @user.roles.map(&:name)
    roles.each { |role_name| @user.remove_role(role_name) }

    @user.add_role(user_params[:role])

    respond_to do |format|
      format.html { redirect_to edit_application_settings_user_management_path(@user), alert: 'Role not Found' }
      format.json { render :show, status: :ok, location: @user }
    end
  end

  def destroy_image
    @user.image.purge

    redirect_to edit_application_settings_user_management_path(@user), notice: 'User was successfully updated.'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :image, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/application_settings/user_managements/edit.html.erb
<%= javascript_packs_with_chunks_tag 'remove_header_margin' %>

<div id="wrapper">
  <%= render 'application_settings/common/sidebar' %>
  <div id="content-wrapper" class="d-flex flex-column">
    <div class="container mt-2">
      <div class="row my-2">
        <h3 class="text-gray-800"><%= t('.title', default: 'User Managements') %>: <%= @user.username %></h3>
      </div>
      <div class="row">
        <div class="card w-100">
          <div class="card-body">
            <%= simple_form_for @user, url: application_settings_user_management_path, method: :patch do |f| %>
              <%= f.input :username %>
              <%= f.input :email %>
              <div class="row">
                <div class="col-3">
                  <p class="mb-1"><%= t('.current_image', default: 'Current Image') %></p>
                  <div class="mb-2">
                    <img src="<%= @user.user_image_url %>" width="90" class="rounded">
                  </div>
                </div>
                <div class="col-6">
                  <%= f.input :image, wrapper: :custom_file %>
                  <% if @user.image.present? %>
                    <div>
                      <%= link_to t('actions.remove', default: 'Remove'), application_settings_user_managements_destroy_image_path(@user), method: :delete, class: 'btn btn-sm btn-danger' %>
                    </div>
                  <% end %>
                </div>
              </div>
              <%= f.submit nil, class: 'btn btn-sm btn-primary' %>
            <% end %>
            <hr />
            <%= simple_form_for @user, url: application_settings_user_managements_update_role_path(@user) do |f| %>
              <div class="form-group mb-3">
                <label><h2 class="h5 text-gray-800"><%= t('.role', default: 'Role') %></h2></label>
                <% Role::ALL_ROLES.each do |role| %>
                  <div class="custom-control custom-radio mb-2">
                    <input type="radio" id="<%= role %>" name="user[role]" class="custom-control-input" value="<%= role %>" <%= @user.has_role?(role.to_sym) ? 'checked' : '' %>>
                    <label class="custom-control-label" for="<%= role %>"><%= role %></label>
                    <small id="emailHelp" class="form-text text-muted"><%= t("role.description.#{role}") %></small>
                  </div>
                <% end %>
              </div>

              <%= f.submit nil, class: 'btn btn-sm btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application_settings/user_managements/index.html.erb
<%= javascript_packs_with_chunks_tag 'remove_header_margin' %>

<div id="wrapper">
  <%= render 'application_settings/common/sidebar' %>
  <div id="content-wrapper" class="d-flex flex-column">
    <div class="container mt-2">
      <div class="row my-2">
        <h3 class="text-gray-800"><%= t('.title', default: 'User Managements') %></h3>
      </div>
      <div class="row">
        <div class="card w-100">
          <div class="card-body">
            <ul class="list-group list-group-flush w-100">
              <% @users.each do |user| %>
                <li class="list-group-item d-flex flex-row align-items-center">
                  <div class="mr-3">
                    <img src="<%= user.user_image_url %>" width="48" class="rounded" />
                  </div>
                  <div>
                    <%= link_to user.username, edit_application_settings_user_management_path(user) %>
                  </div>
                  <div class="d-flex ml-auto align-self-center">
                    <%= link_to edit_application_settings_user_management_path(user), class: 'text-primary mr-2' do %>
                      <i class="far fa-edit"></i>
                    <% end %>
                    <%= link_to application_settings_user_management_path(user), method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="row mt-4">
        <div class="mx-auto">
          <%= paginate @users %>
        </div>
      </div>

    </div>
  </div>
</div>