config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # OmniAuth認証後、email入力を求める処理のため。
  match '/users/:id/finish_signup' => 'omniauth_finished#finish_signup', via: %i[get patch], as: :finish_signup

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'projects#index'
  get '/:ticket_number', to: 'projects#show_with_ticket_number', ticket_number: /[A-Za-z]+-[0-9]+/

  resources :projects do
    resources :sprints, constraints: { format: :json }
    get '/api/closed_sprints', to: 'sprints#closed_sprints', as: 'closed_sprints_api'
    get '/sprints/:id/kanban', to: 'sprints#kanban', as: 'sprint_kanban'
    get '/sprints/:id/kanban/api', to: 'sprints#kanban_api'

    resources :project_ticket_categories, constraints: { format: :json }
    resources :project_ticket_statuses, constraints: { format: :json }

    resources :stories, controller: :tickets, type: Story, constraints: { format: :json } do
      resources :comments
    end
    resources :tasks, controller: :tickets, type: Task, constraints: { format: :json } do
      resources :comments
    end
    member do
      get 'closed_sprints'
      get 'settings'

      get 'users'
      get 'groups'
      get 'project_tags'

      post 'add_group'
      delete 'delete_group/:group_id', action: 'delete_group'
      delete 'delete_image'
    end
  end

  get '/groups_by_name', to: 'groups#search_by_name'

  get '/profiles', to: 'profiles#index'
  patch '/profiles', to: 'profiles#update'
  patch '/profiles/update_password', to: 'profiles#update_password'
  # patch '/profiles/use_gravatar', to: 'profiles#use_gravatar'
  delete '/profiles/image', to: 'profiles#destroy_image'

  namespace :application_settings do
    root to: 'dashboard#index'
    get '/', to: 'dashboard#index'
    post '/', to: 'dashboard#update'

    patch 'group_managements/:id/add_user', to: 'group_managements#add_user', as: 'group_managements_add_user'
    delete 'group_managements/:id/remove_user/:user_id', to: 'group_managements#remove_user',
                                                         as: 'group_managements_remove_user'
    resources :group_managements

    patch 'user_managements/:id/update_role', to: 'user_managements#update_role', as: 'user_managements_update_role'
    delete 'user_managements/:id/destroy_image', to: 'user_managements#destroy_image',
                                                 as: 'user_managements_destroy_image'
    resources :user_managements
  end

  get '/installer', to: 'installer#index', as: 'installer'
  match '/installer', to: 'installer#update', via: %i[post patch]

  get '/health', to: 'health#health'

  # 開発環境でメールを確認するために LetterOpenerWeb エンジンのパスをマウントする
  # これにより以下 URL で開発環境でのメール確認が可能になる
  # http://localhost:3000/letter_opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  title         :string
#  body          :text
#  ticket_prefix :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Project < ApplicationRecord
  has_many :group_projects, dependent: :destroy
  has_many :groups, through: :group_projects
  has_many :users, -> { distinct }, through: :groups
  has_many :sprints, -> { order(created_at: :asc) }
  has_many :project_ticket_statuses
  has_many :project_ticket_categories
  has_many :tags
  has_one_attached :image

  validates :title, presence: true
  validates :ticket_prefix, presence: true, uniqueness: true, format: { with: /[a-zA-Z]/}

  scope :search_by_keyword, -> (keywords) {
    if keywords.present?
      columns = %i[title body]
      where(keywords.split(/[[:space:]]/).reject(&:empty?).map { |keyword|
        columns.map { |a| arel_table[a].matches("%#{keyword}%") }.inject(:or)
      }.inject(:and))
    end
  }

  def project_image_url
    if image.present?
      base64 = Base64.strict_encode64(image.download)

      return "data:#{image.blob.content_type};base64,#{base64}"
    end

    InitialAvatar.avatar_data_uri(title.chars.first, size: 64)
  rescue ActiveStorage::FileNotFoundError
    InitialAvatar.avatar_data_uri(title.chars.first, size: 64)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_authorization_check only: [:new, :create]
  load_and_authorize_resource except: [:new, :create]

  before_action :set_project, only: [
    :show, :edit, :update,
    :settings,
    :users,
    :groups, :add_group, :delete_group,
    :delete_image,
    :project_tags
  ]

  PROJECT_PER_PAGE = 25

  def index
    @projects = @projects.order(updated_at: :desc).search_by_keyword(params[:keywords]).page(params[:page]).per(PROJECT_PER_PAGE)
    # 自分が属している自身のプロジェクトがない場合には作成を促すメッセージを表示するためのフラグ
    @is_not_exits_own_project = @projects.all? { |project| project.is_public && !project.users.include?(current_user) }
  end

  def show
    @opening_sprints = @project.sprints.opening
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    ActiveRecord::Base.transaction do
      @project = Project.new(project_params)
      @project.save!
      @project.group_projects.create!(
        project: @project,
        group: current_user.groups.first
      )
      MasterTicketStatus.all.each do |status|
        ProjectTicketStatus.create(
          project: @project,
          title: status.title,
          sort_order: status.sort_order,
          is_done: status.is_done
        )
      end
      MasterTicketCategory.all.each do |category|
        ProjectTicketCategory.create(
          project: @project,
          title: category.title,
          sort_order: category.sort_order,
          color: category.color
        )
      end
    rescue ActiveRecord::RecordInvalid
      respond_to do |format|
        format.html { render :new }
      end
      return
    end

    redirect_to projects_path, notice: 'Project was successfully created.'
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_with_ticket_number
    ticket_number = params[:ticket_number]

    if ticket_number.match(/([A-Za-z]+)-([0-9]+)/)
      ticket_prefix = Regexp.last_match(1)
      ticket_id = Regexp.last_match(2)
      project = Project.find_by(ticket_prefix: ticket_prefix)
      ticket = Ticket.find_by(project: project, ticket_number: ticket_id)

      redirect_to(root_path, alert: t('message.ticket_not_found', ticket_number: ticket_number, default: "Ticket #{ticket_number} not Found")) && return if ticket.blank?

      redirect_to_with_ticket(ticket_number, project, ticket)
    end

    redirect_to(root_path, alert: t('message.ticket_not_found', ticket_number: ticket_number, default: "Ticket #{ticket_number} not Found")) && return if ticket.blank?
  end

  def destroy
  end

  def closed_sprints
  end

  def settings
  end

  def users
    @users = @project.users
  end

  def groups
    @groups = @project.groups
  end

  def add_group
    group = Group.find(params[:group_id])
    @project.groups << group
  end

  def delete_group
    group = @project.groups.find(params[:group_id])
    @project.groups.destroy(group)

    head :no_content
  end

  def delete_image
    @project.image.purge

    head :no_content
  end

  def project_tags
    @tags = Tag.where(project: @project)
  end

  private

  def project_params
    params.fetch(:project, {}).permit!
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def redirect_to_with_ticket(ticket_number, project, ticket)
    case ticket.type
    when 'Story'
      redirect_to File.join("#{project_path(project)}#", 'stories', ticket.id.to_s)
    when 'Task'
      story = ticket.story
      sprint = story.sprint

      if sprint.blank?
        path = File.join("#{project_path(project)}#", 'stories', story.id.to_s)
        path = "#{path}?message_type=danger&message=#{t('message.task_is_not_in_sprint', ticket_number: ticket_number, default: 'Task is not in Sprint. Currently showing Story.')}"
        redirect_to(path) && return
      end

      redirect_to File.join(project_path(project), 'sprints', sprint.id.to_s, 'kanban#', 'story', story.id.to_s, 'tasks', ticket.id.to_s)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for project do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved.other', count: project.errors.count, resource: 'Project') %></h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, placeholder: t('.placeholder.title', default: 'My awesome project') %>
  <%= f.input :body, as: :text, input_html: { rows: 5 }, placeholder: t('.placeholder.description', default: 'Description format') %>
  <%= f.input :ticket_prefix,
    placeholder: t('.placeholder.ticket_prefix', default: 'e.g.) AWE'),
    hint: t('message.ticket_prefix_description', default: 'Ticket Prefix is an arbitrary string that is added to the beginning of the ticket number.') %>
  <%= f.input :is_public %>

  <div class="action d-flex justify-content-end">
    <%= f.submit nil, class: 'btn btn-primary mr-2' %>
    <%= link_to t('actions.back', default: 'Back'), projects_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/projects/closed_sprints.html.erb
<%= javascript_packs_with_chunks_tag 'remove_header_margin' %>
<%= stylesheet_pack_tag 'closed_sprints', media: 'all' %>
<%= javascript_packs_with_chunks_tag 'closed_sprints' %>

<div id="wrapper">
  <%= render 'commons/sidebar', { project: @project } %>
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content" data-project-id="<%= @project.id %>">
      <router-view />
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="card mx-auto w-50">
      <div class="card-body">
        <div class="text-center">
          <h1 class="mx-auto h4 text-gray-900"><%= t('actions.edit_project', default: 'Edit Project') %></h1>
        </div>
        <%= render 'form', project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container mt-4">
  <div class="row d-flex align-items-center justify-content-between mb-2">
    <div>
      <h1 class="h3 text-gray-800"><%= t('.title', default: 'Projects') %></h1>
    </div>
    <%= link_to t('actions.create_project', default: 'Create Project'), new_project_path, class: 'btn btn-sm btn-primary shadow-sm'%>
  </div>
  <div class="row">
    <%= form_tag projects_path, method: :get, class: 'd-flex w-100 align-items-center justify-content-end' do %>
      <div class="w-25 mr-2">
        <%=
          text_field_tag(
            :keywords,
            params[:keywords],
            placeholder: t('.placeholder_for_search', default: 'Search Projects'),
            class: 'form-control form-control-sm'
          )
        %>
      </div>
      <%= button_tag type: :submit, class: 'btn btn-sm btn-outline-primary' do %>
        <i class="fa fa-search"></i> <%= t('.search', default: 'Search') %>
      <% end %>
    <% end %>
  </div>

  <% if @is_not_exits_own_project %>
    <div class="row mt-3">
      <div class="alert alert-info w-100">
        <%= t(
          '.is_not_exists_own_project',
          default: "Can't find your own project. Create your project with the \"Create Project\" button"
          )
        %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <% if @projects.empty? && params[:keywords].blank? %>
      <div class="mt-4 w-100 bg-gray-200 p-4 rounded">
        <%= t('.project_does_not_exists', default: "Project doesn't exists. Let's create a project with the \"Create Project\" button.") %>
      </div>
    <% end %>
    <% if @projects.empty? && params[:keywords].present? %>
      <div class="mt-4 w-100 bg-gray-200 p-4 rounded">
        <%= t('.project_does_not_exists_when_keywords', default: "Project doesn't exists.") %>
        <%= link_to t('.back_to_projects_index', default: 'Back to project index'), projects_path %>
      </div>
    <% end %>
    <ul class="list-group list-group-flush w-100">
      <% @projects.each do |project| %>
        <li class="list-group-item d-flex flex-row">
          <div class="mr-3">
            <img src="<%= project.project_image_url %>" width="64" class="rounded" />
          </div>
          <div class="d-flex flex-column">
            <div class="mb-1">
              <% if project.is_public %>
                <span class="badge badge-pill badge-info"
                  data-toggle="tooltip" data-placement="top" title="<%= t('.public_project_message', default: 'This is a public project. Non-member users are only allowed to comment on tickets.') %>">
                  <%= t('.is_public', default: 'Public') %> <i class="fas fa-question-circle"></i>
                </span>
              <% end %>
              <%= link_to project.title, project_path(project) %>
            </div>
            <div class=""><%= project.body %></div>
          </div>
          <div class="ml-auto align-self-center">
            <%= link_to edit_project_path(project), class: 'btn btn-sm btn-link' do %>
              <i class="far fa-edit"></i> <%= t('.edit', default: 'Edit') %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @projects %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="card mx-auto w-50">
      <div class="card-body">
        <div class="text-center">
          <h1 class="mx-auto h4 text-gray-900"><%= t('actions.create_project', default: 'Create Project') %></h1>
        </div>
        <%= render 'form', project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/settings.html.erb
<%= javascript_packs_with_chunks_tag 'remove_header_margin' %>
<%= stylesheet_pack_tag 'project_settings', media: 'all' %>
<%= javascript_packs_with_chunks_tag 'project_settings' %>

<div id="wrapper">
  <%= render 'commons/sidebar', { project: @project } %>
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content" data-project-id="<%= @project.id %>">
      <router-view />
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%= javascript_packs_with_chunks_tag 'remove_header_margin' %>
<%= stylesheet_pack_tag 'backlogs', media: 'all' %>
<%= javascript_packs_with_chunks_tag 'backlogs' %>

<div id="wrapper">
  <%= render 'commons/sidebar', { project: @project } %>
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content"
      data-project-id="<%= @project.id %>"
      data-project-title="<%= @project.title %>"
      data-is-public="<%= @project.is_public %>">
      <router-view />
    </div>
    <% if @project.is_public %>
      <div class="alert alert-warning mb-0 fixed-bottom">
        <%= t('.public_project_message', default: 'This is a public project. Non-member users are only allowed to comment on tickets.') %>
      </div>
    <% end %>
  </div>
</div>